AllCops:
  # @see https://docs.rubocop.org/rubocop/configuration.html#pre-processing
  Exclude:
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-performance-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-rake-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-rspec-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-thread-safety-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-v1-0-3-config-rubocop-yml
  
    - coverage/
  
    - '**/*.md'
    - '**/*.markdown'
    - 'benchmark/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

  NewCops: enable
  TargetRubyVersion: 3.2

inherit_from:
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/performance.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/rake.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/rspec.yml
  - https://raw.githubusercontent.com/sashite/sashite-rubocop.rb/v1.0.3/config/rubocop/thread_safety.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-md

Naming/PredicateName:
  Exclude:
    - 'lib/r_spec/clone/expectation_helper/it.rb'
    - 'lib/r_spec/clone/expectation_helper/its.rb'

Metrics/MethodLength:
  Max: 11

Metrics/ParameterLists:
  Max: 6
