inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

  Exclude:
    - spec/**/*.rb

require:
  - rubocop-performance
  - rubocop-md
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Exclude:
    - README.md
    - benchmark/**/*

Naming/PredicateName:
  Exclude:
    - lib/r_spec/clone/expectation_helper/it.rb
    - lib/r_spec/clone/expectation_helper/its.rb

Metrics/ParameterLists:
  Max: 6

Naming/FileName:
  Exclude:
    - benchmark/**/*r_spec-clone*
    - benchmark/**/*test-unit*
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - README.md

Style/ClassAndModuleChildren:
  Exclude:
    - README.md

RSpec/NestedGroups:
  Max: 5

RSpec/FilePath:
  CustomTransform:
    RSpec: r_spec

  Exclude:
    - benchmark/**/*
