AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

  Exclude:
    - '**/*.md'
    - '**/*.markdown'
    - 'benchmark/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Naming/PredicateName:
  Exclude:
    - 'lib/r_spec/clone/expectation_helper/it.rb'
    - 'lib/r_spec/clone/expectation_helper/its.rb'

Metrics/MethodLength:
  Max: 11

Metrics/ParameterLists:
  Max: 6
